version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10

    # parallelism: 4
    # working_directory: ~/functions

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-{{ .Branch }}-

      - run:
          name: install-dependencies
          command: npm install

      - run:
          name: setup-firebase-tools
          command: npm install firebase-tools

      - save_cache:
          paths:
            - node_modules
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: build
          command: |
              npm run build

      - run:
          name: copy-firebase.json
          command: cp firebase.json ./dist/firebase.json

      - run:
          name: copy-firebase.json
          command: cp firebase.json ./dist/firebase.json

      - deploy:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN